### ISSUE TITLE
Values in some graphs are negative

### ISSUE THREAD

**Issue by ProfessorStoke** [rpandey1234/Covid19Tracker#1]
Examples:
- Negative graph for Alaska on April 14th 2020 shows a value of -213
- Deaths graph for Colorado on May 14th 2020 shows a value of -213
- Negative graph for Connecticut on June 23 2020 shows a value of -1,608
- Negative graph for DC on May 24th 2020 shows a value of -11,447

**Comment by rpandey1234** [comment]
These look to be data reporting errors by each state, as per https://covidtracking.com/data. Some examples:

- Connecticut: "On June 24, CT removed 2770 previously reported tests due to correction of a data error. Negatives decreased as a result."
- DC: "Total tests reported by DC dropped by about 11,000 from 5/24 to 5/25."

In any case, this does make the graphs harder to interpret, so we should add some defensive checks. I added a way to turn these negative values to 0 so they won't detract from the spark chart: https://github.com/rpandey1234/Covid19Tracker/commit/9f8a0b74fce8db283fbd7cf43c9e2e6d8b6024be.
